### ISSUE TITLE
API picks sensible defaults for variables that aren't defined

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/bagelapi#12]

**Comment by surchs** [comment]
I am not sure if the goal here was to close this with https://github.com/neurobagel/bagelapi/pull/17. It seems to be checked off in #1 . @rmanaem could you take a look and see if this is still open. If it is open, could you put in the description which parameters you still need good defaults for?

**Comment by rmanaem** [comment]
Yea you're right. I think it was left out of the first PR.
