### ISSUE TITLE
Make GET crud function send POST request to Stardog API

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelapi#16]
1. - [x] The get function in crud.py module will make send a POST request using httpx library to the Stardog API and return the response.
2. - [x] The get_query method in main module will wait on get function from crud.py and return the response as a JSON if there are no errors.
3. - [x] The behaviour when no query params are passed to our API is to return all data in the database.
4. - [x] Write test for Tasks 2 and 3 that asserts status code 200 (and/or maybe that response is a json) when a `GET` request is sent with `/query/`.
5. - [x] Add comments

**Comment by rmanaem** [comment]
Check commit: 56cb62c2a0a0e7cc44f41fc23771e61e4124d916
