### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/bagelapi#21]
The README should have information on how one can:

- [x] setup a local dev environment (venv + pip)
- [x] launch the API (uvicorn ... + set environment variables)
- [x] how to run the pytest tests (env variables are set + the server is reachable?)

**Comment by alyssadai** [comment]
Embed repo coverage badge from Coveralls, available [here](https://coveralls.io/github/neurobagel/bagelapi).

**Comment by rmanaem** [comment]
@alyssadai @surchs Do you think we need a section explaining reaching/connecting/accessing the server whether it'd be through VPN or something other way in the README? or what we currently have is enough?

**Comment by surchs** [comment]
> or what we currently have is enough?

I think we have nothing right now, no? Or is there some draft you're referring to?
I think you could have a note that the API is meant to interface with a graph store like Stardog that needs to be run separately. I wouldn't tie the README to our current deployment, and I think it's more important to document the environment setup and how to run  the tests than how to deploy Stardog. So my vote is to leave out the graph stuff.

**Comment by rmanaem** [comment]
It seems I didn't commit and push the changes. You should be able to see what I was referring to now.

**Comment by surchs** [comment]
I guess you're referring to https://github.com/neurobagel/bagelapi/tree/972e468d2424f7b0c20294ae9f7d4c8469421c55 ?
That looks good to me. But please open a PR (draft if you want) to discuss this.
