### ISSUE TITLE
Implement cognitive assessment tools as a query parameter

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelapi#33]
- [x] Implement cognitive assessment in create_query function of utility.py module
- [x] Add cognitive assessment as a field in QueryModel of models.py module
- [x] Update get_query path operation of query.py router and get function of crud.py module to reflect the addition of cognitive assessment
- [x] test parameter implementation/functionality

**Comment by surchs** [comment]
Moving this to "Blocked" because there currently isn't any cognitive assessment data in the graph to test against.

**Comment by alyssadai** [comment]
See https://github.com/neurobagel/bagelapi/issues/54#issuecomment-1379744879
