### ISSUE TITLE
Implement a minimum number of (imaging) sessions as a query parameter

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelapi#34]
- [x] Implement minimum number of sessions in create_query function of utility.py module
- [x] Add minimum number of sessions as a field in QueryModel of models.py module
- [x] Update get_query path operation of query.py router and get function of crud.py module to reflect the addition of minimum number of sessions
- [x] test parameter implementation/functionality

**Comment by alyssadai** [comment]
Personally, I think a positive integer is fine (`ge=1` I guess? If we anticipate having subjects in the graph with no imaging data however, we could even do `ge=0`). We didn't end up enforcing an upper limit on age either. If the user enters 200 or something, I think it's okay for the API to just return nothing.

**Comment by surchs** [comment]
One thing to keep in mind also is that we don't want to filter only imaging sessions here in the future. We filter # of imaging sessions for now because we don't have the demographic information at the level of the session yet. But that will change soon. So I would make the parameter more generic as "given these cohort criteria, how many sessions should at least exist for a subject in order for you to be interested in it?"
