### ISSUE TITLE
Create queries that only return aggregate information and access information

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelapi#35]
When I run a cohort query through the API, the results should not contain any demographic metadata (like age, sex, etc) but instead should contain:

- [x] #49
- [x] #50
- [x] #51
- [x] #52

**Comment by rmanaem** [comment]
@alyssadai Mind if I take this?

**Comment by surchs** [comment]
I think this should be split into several issues - there's quite a bit of work behind each of the points. I added the Epic label for now, and we can discuss how to break it down into more manageable chunks
