### ISSUE TITLE
Setup code coverage reporting

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelapi#38]
When I open a PR, I would like to get a report on whether the changes will increase or decrease the current code coverage, so we can keep an eye on test coverage during the review.

I think https://github.com/apps/codecov and https://about.codecov.io/ are good solutions to look into for that.

**Comment by alyssadai** [comment]
[Coveralls](https://github.com/marketplace/actions/coveralls-github-action) seems like another good option that works similarly to Codecov (but the reports aren't _quite_ as beautiful)

**Comment by surchs** [comment]
Yeah, that also looks nice. Want to take another look if codecov lets you in and otherwise set up coveralls here?
