### ISSUE TITLE
Only run test suite in pull requests

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelapi#42]
Our excellent test suite currently [runs on two events](https://github.com/neurobagel/bagelapi/blob/main/.github/workflows/test.yaml): push and pull_request ([see also](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)). I think they should only run for pull _request so we don't run them twice during a PR.

**Comment by rmanaem** [comment]
Good call, I'll take care of it.

**Comment by rmanaem** [comment]
After some consideration, I think It's better to have both. The workflow runs on push come in handy, especially when modifying/updating the workflow itself (test.yaml).
[Unfortunately, it's not possible to trigger an action on push or pull request but not both](https://github.com/orgs/community/discussions/26276).

**Comment by surchs** [comment]
Hhm, I don't think that's a very common thing though. At the moment, we very rarely - if every - push directly to main. But I see your point about having a way to trigger the workflow. Maybe what we can do instead is enable a manual launch of the workflow for these rare situations: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

What do you think?

**Comment by rmanaem** [comment]
Interesting, I like it!
