### ISSUE TITLE
Return FS paths for subjects that match a query

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelapi#51]
To do:

- [x] #54
- [x] Query template should be updated to return paths at the **session-level** regardless of the total number of unique matching subjects
- [x] Update `AggDatasetResponse` model
- [x] Update `get` function in `crud.py` module
- [x] ~Test that corresponding field in response body (e.g., `subject_paths`) returns a list~
- [x] Update `test_data` in `test_query.py` module

**Comment by surchs** [comment]
blocked by #54

**Comment by alyssadai** [comment]
Now unblocked, see https://github.com/neurobagel/bagelapi/issues/54#issuecomment-1379744879

**Comment by rmanaem** [comment]
Regarding 
>  Test that corresponding field in response body (e.g., subject_paths) returns a list

see #60
