### ISSUE TITLE
Decision of GET or POST route in our API for query

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelapi#6]
Do we want to implement a `GET` or `POST` route for writing a SPARQL query based on client inputs + sending it to the Stardog API (presumably as a `POST` request on the graph end)?

**Comment by alyssadai** [comment]
- GET is preferred, how would we implement a data model?

**Comment by surchs** [comment]
How would I consume your API as a user? If someone shares a URL that includes the query string with me and I paste that into the browser, should that work / return something? Or should I consult the developer docs to see what format the request payload should have and then generate it for you?

**Comment by alyssadai** [comment]
> If someone shares a URL that includes the query string with me and I paste that into the browser, should that work / return something?  

No, you would specify each variable that you want to filter for in the SPARQL query (e.g., sex) as a key-value pair in our GET URL path. Our API will create a SPARQL query based on these parameters and sent the formed query to Stardog.

> Or should I consult the developer docs to see what format the request payload should have and then generate it for you?

For now, this is not necessary. We have a function that contains a SPARQL query template to use.
