### ISSUE TITLE
Set up dev environment and conventions for code quality

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelapi#7]
flake8?

**Comment by rmanaem** [comment]
- Linter: flake 8
- Formatter: black
WIll be configured in pre-commit file

**Comment by alyssadai** [comment]
- Google docstring for docstring convention

**Comment by alyssadai** [comment]
For now, use a Python environment

**Comment by rmanaem** [comment]
black and flake8 are added as pre-commit hooks, Refer to 437b8c6ccfefc1dadbae121fbf3bb53628383528
